### ISSUE TITLE
Nanoid() with negative argument panics

### ISSUE THREAD

**Issue by breml** [matoous/go-nanoid#10]
If `Nanoid()` function is called with a negative argument, the function panics.

E.g.

```
gonanoid.Nanoid(-1)
```

panics with:

```
panic: runtime error: makeslice: len out of range [recovered]                           
        panic: runtime error: makeslice: len out of range 
```

The function signature already allows to return an error so I suggest to return an error in this case instead of letting it panic.

Additionally, due to the (in my opinion not very Go ideomatic) function signature, it is possible to call this function with more than one argument. I suggest to return an error in this case as well.

I can provide a PR if you wish.

**Comment by breml** [comment]
@matoous has there been a fix for this issue? Why is it closed without any comment?

**Comment by matoous** [comment]
Hi! Yes, sorry, forgot to add a comment here.

I fixed the issue, it's a part of last tag.

Thanks for raising the issue!
