### ISSUE TITLE
Non ASCII ID's

### ISSUE THREAD

**Issue by MrOzean** [matoous/go-nanoid#13]
I try to use this library to generate simple human readable ID's on my native language.
Using library according to documentation with non ascii alphabet:
` id, err := gonanoid.Generate("абвгдежиклмнпрстуфхшэюя0123456789-", 10) `
Gives me byte garbage with wrong length

> 3ю�ѽ�д0
�Џ�51�б7
���Ѷ0�Ѻ�

Instead normal ID like:

> 2юбнг4внеэ

Original implementation has no this problem [https://zelark.github.io/nano-id-cc/](url)

**Comment by matoous** [comment]
Fixed by: https://github.com/matoous/go-nanoid/pull/15
