### ISSUE TITLE
Importing v2.0.0

### ISSUE THREAD

**Issue by vaidd4** [matoous/go-nanoid#20]
Hi,
When I `go get github.com/matoous/go-nanoid`  it retrieves the version 1.5.0.
```
go: downloading github.com/matoous/go-nanoid v1.5.0
go: github.com/matoous/go-nanoid upgrade => v1.5.0
```
I would like to use the most recent version (aka 2.0.0) but I'm not sure how to download/add it to my project.

**Comment by matoous** [comment]
Hi!

Not sure if there's any other way but I think you need to use following command: `go get github.com/matoous/go-nanoid/v2`

**Comment by vaidd4** [comment]
I'm getting the following error : 
```
go get github.com/matoous/go-nanoid/v2: module github.com/matoous/go-nanoid@upgrade found (v1.5.0), but does not contain package github.com/matoous/go-nanoid/v2
```

**Comment by matoous** [comment]
Yeah, sorry, didn't have much experience upgrading packages to v2 so I had a few mistakes in the repo. Should be all fixed as of now.
