### ISSUE TITLE
Generate is stuck indefinitely for size=1

### ISSUE THREAD

**Issue by pastx** [matoous/go-nanoid#49]
I might have missed something from the usage docs, but generating a random id of size 1 doesn't work.
`prefix, err := nanoid.Generate(prefixAlphabet, 1)` never finishes.

Context: I want to generate a longer ID with the first character being from a different alphabet.

**Comment by adiatma85** [comment]
Hmm, I can not reproduce this issue. Here's my code

```go
package main

import (
	"fmt"

	goNanoId "github.com/matoous/go-nanoid/v2"
)

const (
	Base62Chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
)

func main() {
	// Generate shorten url
	shortenUrl, err := goNanoId.Generate(Base62Chars, 2)
	if err != nil {
		panic(err)
	}

	fmt.Println("Result: ", shortenUrl)
}
```

And here is the result:
![image](https://github.com/matoous/go-nanoid/assets/57523711/c2b8cc78-4b2a-405f-9459-97430c3918b8)

**Comment by matoous** [comment]
Neither could I. @pastx if you could share an example I would be happy to take a look.

**Comment by adiatma85** [comment]
@yesudeep your codes works fine in my machine 🤔 (I am running on `go1.22.3``)

**Comment by pastx** [comment]
> Neither could I. @pastx if you could share an example I would be happy to take a look.

```
package generate_test

import (
	nanoid "github.com/matoous/go-nanoid"
	"testing"
)

func TestGenerateResourceID(t *testing.T) {
	prefixAlphabet := "abcdefghijklmnopqrstuvwxyz"
	_, _ = nanoid.Generate(prefixAlphabet, 1)
}
```

This test is stuck forever for me. 

When I change the second arg to `2`, it works fine.

**Comment by adiatma85** [comment]
> @adiatma85 which operating system and architecture are you using?

Sorry for the late response @yesudeep 
I am using Linux, this is the full output ``go version go1.22.3 linux/amd64``

**Comment by matoous** [comment]
Heya, I was able to replicate on v1, fixed patch here: https://github.com/matoous/go-nanoid/releases/tag/v1.5.1

You might still want to consider using v2 instead.
